// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Server = require("react-dom/server");
var Addons = require("@storybook/addons");

var component = ReasonReact.statelessComponent("ShowMarkup");

function make(children) {
  var newrecord = component.slice();
  newrecord[/* didMount */4] = (function () {
      var channel = Addons.default.getChannel();
      channel.emit("ulrikstrid/storybook-markup/show_markup", Server.renderToStaticMarkup(children));
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function () {
      return children;
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.children);
      }));

exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
