// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Rehype = require("rehype");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var RehypeFormat = require("rehype-format");
var Addons = require("@storybook/addons");

function textElement(prim) {
  return prim;
}

var markupPanelStyle = {
  color: "#444",
  fontFamily: "Arial",
  fontSize: "14px",
  margin: "10px",
  overflow: "auto",
  width: "100%"
};

var component = ReasonReact.reducerComponent("Markup");

function make(api, channel, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return React.createElement("div", {
                  style: markupPanelStyle
                }, React.createElement("pre", undefined, React.createElement("code", undefined, self[/* state */2][/* text */0])));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* text */""];
    });
  newrecord[/* reducer */12] = (function (action, _) {
      return /* Update */Block.__(0, [/* record */[/* text */action[0]]]);
    });
  newrecord[/* subscriptions */13] = (function (self) {
      var handler = function (text) {
        var __x = Rehype();
        var __x$1 = __x.data("settings", {
              fragment: true
            });
        var __x$2 = __x$1.use(RehypeFormat);
        __x$2.process(text, (function (_, file) {
                return Curry._1(self[/* send */4], /* AddMarkup */[file.contents]);
              }));
        return /* () */0;
      };
      return /* :: */[
              /* Sub */[
                (function () {
                    channel.on("ulrikstrid/storybook-markup/show_markup", handler);
                    return "ulrikstrid/storybook-markup/show_markup";
                  }),
                (function (token) {
                    api.onStory((function () {
                            return Curry._1(self[/* send */4], /* AddMarkup */[""]);
                          }));
                    channel.removeListener(token, handler);
                    return /* () */0;
                  })
              ],
              /* [] */0
            ];
    });
  return newrecord;
}

var Markup = /* module */[
  /* markupPanelStyle */markupPanelStyle,
  /* component */component,
  /* make */make
];

Addons.default.register("ulrikstrid/storybook-markup", (function (api) {
        Addons.default.addPanel("ulrikstrid/storybook-markup/panel", {
              title: "Markup",
              render: (function () {
                  return ReasonReact.element(/* None */0, /* None */0, make(api, Addons.default.getChannel(), /* array */[]));
                })
            });
        return /* () */0;
      }));

exports.textElement = textElement;
exports.Markup = Markup;
/* component Not a pure module */
