// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as HtmlBeautify from "html-beautify";
import * as Addons from "@storybook/addons";

var markupPanelStyle = {
  color: "#444",
  fontFamily: "Arial",
  fontSize: "14px",
  margin: "10px",
  overflow: "auto",
  width: "100%"
};

function text(prim) {
  return prim;
}

var component = ReasonReact.reducerComponent("Markup");

function make(api, channel, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return React.createElement("div", {
                  style: markupPanelStyle
                }, React.createElement("pre", undefined, React.createElement("code", undefined, HtmlBeautify(self[/* state */2][/* text */0]))));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* text */""];
    });
  newrecord[/* reducer */12] = (function (action, _) {
      return /* Update */Block.__(0, [/* record */[/* text */action[0]]]);
    });
  newrecord[/* subscriptions */13] = (function (self) {
      var handler = function (text) {
        return Curry._1(self[/* send */4], /* AddMarkup */[text]);
      };
      return /* :: */[
              /* Sub */[
                (function () {
                    channel.on("ulrikstrid/storybook-markup/show_markup", handler);
                    return "ulrikstrid/storybook-markup/show_markup";
                  }),
                (function (token) {
                    api.onStory((function () {
                            return Curry._1(self[/* send */4], /* AddMarkup */[""]);
                          }));
                    channel.removeListener(token, handler);
                    return /* () */0;
                  })
              ],
              /* [] */0
            ];
    });
  return newrecord;
}

var Markup = /* module */[
  /* markupPanelStyle */markupPanelStyle,
  /* text */text,
  /* component */component,
  /* make */make
];

Addons.default.register("ulrikstrid/storybook-markup", (function (api) {
        Addons.default.addPanel("ulrikstrid/storybook-markup/panel", {
              title: "Markup",
              render: (function () {
                  return ReasonReact.element(/* None */0, /* None */0, make(api, Addons.default.getChannel(), /* array */[]));
                })
            });
        return /* () */0;
      }));

export {
  Markup ,
  
}
/* component Not a pure module */
