// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE

import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Server from "react-dom/server";
import * as Addons from "@storybook/addons";

var component = ReasonReact.statelessComponent("ShowMarkup");

function make(children) {
  var newrecord = component.slice();
  newrecord[/* didMount */4] = (function () {
      var channel = Addons.default.getChannel();
      channel.emit("ulrikstrid/storybook-markup/show_markup", Server.renderToStaticMarkup(children));
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function () {
      return children;
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.children);
      }));

export {
  component ,
  make ,
  $$default ,
  $$default as default,
  
}
/* component Not a pure module */
